### ISSUE TITLE
Add the ability to take snapshots of views (especially for failed tests)

### ISSUE THREAD

**Issue by plivesey** [linkedin/LayoutTest-iOS#1]

**Comment by liamjdouglas** [comment]
Started taking a look at this here, https://github.com/liamjdouglas/LayoutTest-iOS/tree/issue-1-adding-snapshots. Idea so far is that we'll take a snapshot of each failing test and save it into a directory in the derived data with the structure, /LayoutTestImages/{ClassName}/{MethodName}/{ImageName}.png.
The path to the folder will be output after each test case class and an index.html file is also generated for each class which contains the failure reasons, images and the data that the tests failed with.
Currently planning to have this in LYTLayoutTestCase or would you prefer that snapshot test cases have their own class which subclasses LYTLayoutTestCase?

**Comment by plivesey** [comment]
This looks really promising. I like the idea of outputting HTML.

I'd say let's add this to LYTLayoutTestCase (but functionality in a separate class). I think it should be enabled by default since it seems like a useful tool. I had a brief look over your code, and have a few thoughts:
- Sometimes with failures, everything fails and you end up with 1000+ failures. Any performance concerns? Do you think we should limit the failures to some reasonable number by default and stop taking screenshots? Not sure if this is necessary...if you're running on the simulator, 1000 images should be pretty trivial?
- I think we should add an option to LYTConfig to turn this on or off
- It looks like the data is being included in the filename. This can be really long for some views. Perhaps we should include a hash here and include the data in the HTML page?

Looking forward to the pull request.

**Comment by liamjdouglas** [comment]
I've started splitting out the functionality today and started putting it under test.

- There will be a performance hit if the number of failing tests reach the 1000s, probably even the high hundreds. I'll take a look at some options see if the image creation can be optimised or like you say limit the number of images saved. Could be limited to 10 per test method or 100 per class something like that?
- Yep no problem I'll add that in.
- Yep good idea, I'll switch it to a hash.

**Comment by plivesey** [comment]
One other thought. This only catches errors thrown by the library's automatic tests, not by custom tests. For instance:

```
runLayoutTests() { (view: MyView, data: [NSObject: AnyObject], context: Any?) {
    XCTAssertEqual(view.lyt_height, 30)
}
```

If this assertion fails, we won't generate a screenshot. Do you know of anyway to catch test failures like this?
I tried using a try catch, but it doesn't work here.

**Comment by liamjdouglas** [comment]
At the moment I'm using
`- (void)recordFailureWithDescription:(NSString *)description inFile:(NSString *)filePath atLine:(NSUInteger)lineNumber expected:(BOOL)expected {`
to catch the all the failures. From what I've seen so far and from the docs I think this should catch all XCTAssert failures.

>  @method -recordFailureWithDescription:inFile:atLine:expected:
 Records a failure in the execution of the test and is used by all test assertions.

I've tried in the sample app in SampleTableViewCellLayoutTests replacing the contents of runLayoutTests() with multiple `XCTAssertFalse(true)` and `recordFailureWithDescription:inFile:atLine:expected` is called once for each failure. Currently this will save one image per iteration of runLayoutTests() with different data/view size that has a failing test.
Does that sound ok?

**Comment by plivesey** [comment]
Nice. I didn't know about this method. This seems like exactly what we're looking for.

**Comment by liamjdouglas** [comment]
Added pull request #7

**Comment by plivesey** [comment]
I'll take a look today. Thanks!

**Comment by plivesey** [comment]
A bit slow getting round to reviewing all the code (busy start to the week)...probably some will come in chunks. Excited to get this in though...sorry about being slow to review.

**Comment by plivesey** [comment]
Ok...first pass of the review done. Added a few comments here and there, but overall, looks really good.

Another thing: are you planning on squashing these commits for the merge? I'm not sure what the general practice is, but seems like there are a bunch of intermediate commits which may not compile/are buggy.
I'm used to working on a trunk model, so maybe the open source community tends to prefer something different and we shouldn't squash?

**Comment by liamjdouglas** [comment]
Probably best to squash them and then merge it in. Let me know if there's anything else to update and once ready to merge I'll squash.

**Comment by plivesey** [comment]
Fixing in pull request - #9 Thanks @liamjdouglas for the code.
