### ISSUE TITLE
Podfile unable to find a specification for `LayoutTest/Swift` 

### ISSUE THREAD

**Issue by randyfong** [linkedin/LayoutTest-iOS#14]
I am trying to run the example found in GitHub, but I am running into a problem with my podfile.

Anybody have a suggestion? The project is the exact one from GitHub and I can see `LayoutTest/Swift` in finder and in the project directory in xCode.

**## Error from Command Line**

\[!] The Podfile does not contain any dependencies.
AMAC02NXBTSG3QC:LayoutTest-iOS-master randall.fong$ pod install
Analyzing dependencies
[!] Unable to find a specification for `LayoutTest/Swift`

**## Podfile Definition**

target 'LayoutTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LayoutTest

  target 'LayoutTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'LayoutTest'
  end

end

target 'LayoutTestBase' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LayoutTestBase
  pod 'LayoutTest/Swift'

end

<img width="611" alt="directory" src="https://cloud.githubusercontent.com/assets/948802/16850961/41f80308-49b6-11e6-947a-de3a7069ad21.png">
<img width="1074" alt="xcodeproject" src="https://cloud.githubusercontent.com/assets/948802/16850969/47f85afa-49b6-11e6-9c27-b1912d27fbff.png">

**Comment by plivesey** [comment]
I'm a bit confused with what you're trying to do here. It looks like you added this Podfile right? This Podfile can't work because there's a circular dependency:

LayoutTest depends on LayoutTestBase (from the LayoutTest.podspec)
And here, you're trying to make LayoutTestBase depend on LayoutTest/Swift

Perhaps you're looking for the sample app?

**Comment by randyfong** [comment]
Hi Peter,


When I ran the "pod init" that is what I got after adding the statement in the inner loop per what I thought were the instructions.


It's the first time I've run an init since I upgraded my version of cocoa pods.


Perhaps you can send me what information should be in the pod file and I can try the pod install again.


Randy



-----Original Message-----

**Comment by plivesey** [comment]
Huh...honestly, not familiar with what `$ pod init` does...looks like it creates a blank podspec? Either way, to test the main library, you don't need to run any pod commands. You can just open LayoutTest.xcodeproj and run `cmnd+u` to run tests.

For the sample app:

```
$ cd SampleApp
$ open SampleApp.xcworkspace/
cmnd+u to run tests
```

The sample app does use cocoapods, but everything is commited to the repo, so you don't need to run `pod install`

**Comment by randyfong** [comment]
OK. I'll try that later on today and let you know how it comes out. Thanks for the help!

**Comment by randyfong** [comment]
I downloaded the latest version and it does not have a workspace.

AMAC02NXBTSG3QC:LayoutTest-iOS-master randall.fong$ ls -la

total 64
drwxr-xr-x@ 15 randall.fong  562225435   510 Jul  1 14:27 .
drwx------+ 76 randall.fong  562225435  2584 Jul 17 09:02 ..
-rwxr-xr-x@  1 randall.fong  562225435   200 Jul  1 14:27 .gitignore
-rwxr-xr-x@  1 randall.fong  562225435  9140 Jul  1 14:27 LICENSE
drwxr-xr-x@  7 randall.fong  562225435   238 Jul  1 14:27 LayoutTest
-rwxr-xr-x@  1 randall.fong  562225435  1530 Jul  1 14:27 LayoutTest.podspec
drwxr-xr-x@  5 randall.fong  562225435   170 Jul  1 14:27 LayoutTest.xcodeproj
drwxr-xr-x@  9 randall.fong  562225435   306 Jul  1 14:27 LayoutTestBase
-rwxr-xr-x@  1 randall.fong  562225435  1288 Jul  1 14:27 LayoutTestBase.podspec
drwxr-xr-x@ 14 randall.fong  562225435   476 Jul  1 14:27 LayoutTestTests
-rwxr-xr-x@  1 randall.fong  562225435   466 Jul  1 14:27 NOTICE
-rwxr-xr-x@  1 randall.fong  562225435  3379 Jul  1 14:27 README.md
drwxr-xr-x@  8 randall.fong  562225435   272 Jul  1 14:27 SampleApp
drwxr-xr-x@  4 randall.fong  562225435   136 Jul  1 14:27 TestProjects
drwxr-xr-x@ 10 randall.fong  562225435   340 Jul  1 14:27 docs

AMAC02NXBTSG3QC:LayoutTest-iOS-master randall.fong$ cd SampleApp

AMAC02NXBTSG3QC:SampleApp randall.fong$ ls -la

total 16
drwxr-xr-x@  8 randall.fong  562225435   272 Jul  1 14:27 .
drwxr-xr-x@ 15 randall.fong  562225435   510 Jul  1 14:27 ..
drwxr-xr-x@  6 randall.fong  562225435   204 Jul  1 14:27 CatalogSample
-rwxr-xr-x@  1 randall.fong  562225435   220 Jul  1 14:27 Podfile
-rwxr-xr-x@  1 randall.fong  562225435  1444 Jul  1 14:27 Podfile.lock
drwxr-xr-x@ 12 randall.fong  562225435   408 Jul  1 14:27 SampleApp
drwxr-xr-x@  3 randall.fong  562225435   102 Jul  1 14:27 SampleApp.xcodeproj
drwxr-xr-x@  5 randall.fong  562225435   170 Jul  1 14:27 SampleAppTests

AMAC02NXBTSG3QC:SampleApp randall.fong$ open SampleApp.xcworkspace/

The file /Users/randall.fong/Desktop/LayoutTest-iOS-master/SampleApp/SampleApp.xcworkspace does not exist.

**Comment by randyfong** [comment]
I downloaded the latest version and it does not have a workspace.

AMAC02NXBTSG3QC:LayoutTest-iOS-master randall.fong$ ls -la

total 64
drwxr-xr-x@ 15 randall.fong  562225435   510 Jul  1 14:27 .
drwx------+ 76 randall.fong  562225435  2584 Jul 17 09:02 ..
-rwxr-xr-x@  1 randall.fong  562225435   200 Jul  1 14:27 .gitignore
-rwxr-xr-x@  1 randall.fong  562225435  9140 Jul  1 14:27 LICENSE
drwxr-xr-x@  7 randall.fong  562225435   238 Jul  1 14:27 LayoutTest
-rwxr-xr-x@  1 randall.fong  562225435  1530 Jul  1 14:27 LayoutTest.podspec
drwxr-xr-x@  5 randall.fong  562225435   170 Jul  1 14:27 LayoutTest.xcodeproj
drwxr-xr-x@  9 randall.fong  562225435   306 Jul  1 14:27 LayoutTestBase
-rwxr-xr-x@  1 randall.fong  562225435  1288 Jul  1 14:27 LayoutTestBase.podspec
drwxr-xr-x@ 14 randall.fong  562225435   476 Jul  1 14:27 LayoutTestTests
-rwxr-xr-x@  1 randall.fong  562225435   466 Jul  1 14:27 NOTICE
-rwxr-xr-x@  1 randall.fong  562225435  3379 Jul  1 14:27 README.md
drwxr-xr-x@  8 randall.fong  562225435   272 Jul  1 14:27 SampleApp
drwxr-xr-x@  4 randall.fong  562225435   136 Jul  1 14:27 TestProjects
drwxr-xr-x@ 10 randall.fong  562225435   340 Jul  1 14:27 docs

AMAC02NXBTSG3QC:LayoutTest-iOS-master randall.fong$ cd SampleApp

AMAC02NXBTSG3QC:SampleApp randall.fong$ ls -la

total 16
drwxr-xr-x@  8 randall.fong  562225435   272 Jul  1 14:27 .
drwxr-xr-x@ 15 randall.fong  562225435   510 Jul  1 14:27 ..
drwxr-xr-x@  6 randall.fong  562225435   204 Jul  1 14:27 CatalogSample
-rwxr-xr-x@  1 randall.fong  562225435   220 Jul  1 14:27 Podfile
-rwxr-xr-x@  1 randall.fong  562225435  1444 Jul  1 14:27 Podfile.lock
drwxr-xr-x@ 12 randall.fong  562225435   408 Jul  1 14:27 SampleApp
drwxr-xr-x@  3 randall.fong  562225435   102 Jul  1 14:27 SampleApp.xcodeproj
drwxr-xr-x@  5 randall.fong  562225435   170 Jul  1 14:27 SampleAppTests

AMAC02NXBTSG3QC:SampleApp randall.fong$ open SampleApp.xcworkspace/

The file /Users/randall.fong/Desktop/LayoutTest-iOS-master/SampleApp/SampleApp.xcworkspace does not exist.

**Comment by plivesey** [comment]
Huh...yeah, it looks like for some reason that's not in git. Unclear why.

Try:

```$ cd SampleApp
$ pod install
$ open SampleApp.xcworkspace```

**Comment by plivesey** [comment]
So, turns out I had .xcworkspace in my global ignore.

I've now committed the workspace, so you should be able to run the sample app without needing to run any pod commands.

**Comment by randyfong** [comment]
OK. Perhaps I'll try again this weekend.


Thanks!


Randy



-----Original Message-----

**Comment by plivesey** [comment]
Going to close this since there doesn't look like new updates? Hope you worked it out @randyfong? Feel free to reopen.

**Comment by randyfong** [comment]
Hi Peter,


I haven't had the time to check it out, yet.


Thanks for your help.


Go ahead and close for now.


Randy



-----Original Message-----
