### ISSUE TITLE
Print path to html report on test failure

### ISSUE THREAD

**Issue by brennantaylor** [linkedin/LayoutTest-iOS#21]
It would be nice if the path was more easily accessible. If it were printed as part of the test I could click it in the console and open it directly which would be awesome!

**Comment by plivesey** [comment]
There is code to do this, but it never gets called:

```
- (void)testBundleDidFinish:(NSBundle *)testBundle {
    if (self.failingTestsSnapshotFolders.count > 0) {
        SimpleLog(@"\nSnapshots of failing tests can be found in:\n");
        for (NSString *path in self.failingTestsSnapshotFolders) {
            SimpleLog(@"%@\n", path);
        }
        [self.failingTestsSnapshotFolders removeAllObjects];
    }
}
```

**Comment by plivesey** [comment]
I'm taking a look why...

**Comment by plivesey** [comment]
It looks like `testBundleDidFinish:` is just never called...but I don't know why this is? I don't presume you have any experience here @brennantaylor?

**Comment by brennantaylor** [comment]
@plivesey I am not terribly familiar. Maybe try `testSuiteDidFinish(_:)`?

**Comment by plivesey** [comment]
Good idea...I'll try that.

**Comment by plivesey** [comment]
That works, but gets called for every class. Maybe we should print out the path once per file if any of the tests fail for now? At least thats better than what we currently have...

**Comment by brennantaylor** [comment]
I'd be happy with that.

In particular appcode buckets the console output by test so that would make me super happy.

**Comment by plivesey** [comment]
Great. I'll do this with the swift 3 migration work.

**Comment by plivesey** [comment]
#29

**Comment by plivesey** [comment]
Printing the path on every test suite failure. Opened #28 to track the issue of not being able to print on test bundle finish.
