### ISSUE TITLE
LYTBoolValues() always renders as 1 in html report

### ISSUE THREAD

**Issue by brennantaylor** [linkedin/LayoutTest-iOS#22]
LayoutTest 1.3.0

Both true and false are being passed to `viewForData`, but in the html report it is always printing as `1`.

**Comment by plivesey** [comment]
Reproduced. Will take a look.

**Comment by plivesey** [comment]
https://github.com/linkedin/LayoutTest-iOS/pull/23

**Comment by plivesey** [comment]
Fixed. Will get into the next release. Hopefully with the other bug fix, but can't work out whats wrong there.
