### ISSUE TITLE
false bool values not taken into account while laying out views

### ISSUE THREAD

**Issue by buppal** [linkedin/LayoutTest-iOS#24]
`LYTBoolValues()` adds both `true` and `false`. But the views in the test are rendered for only `true` values. The test does not render any views for `false` values.

**Comment by plivesey** [comment]
I can't reproduce this locally. When I run the SampleAppTests it uses BoolValues:

```
    public class func dataSpecForTest() -> [NSObject: AnyObject] {
        return [
            "text": LYTStringValues(),
            "buttonText": LYTStringValues(),
            "buttonEnabled": LYTBoolValues(),
            "imageType": LYTDataValues(values: ["linkedin", "garbageString", NSNull()])
        ]
    }
```

If I put a break point on line 40 and `po data["buttonEnabled"]`, eventually (after a few tries) I see:

```▿ Optional<AnyObject>
  - Some : 1

▿ Optional<AnyObject>
  - Some : 0
```

It does return true multiple times in a row before moving to false though. Can you send me some sample code that reproduces the issue?

**Comment by buppal** [comment]
Yes, that prints fine in the debugger, even for me. I see true/false being printed alternatively. But the view is not rendered according to the false value. If you have a button and label, and you set the button to hidden according to the bool value, it won't get hidden.

**Comment by plivesey** [comment]
It looks like the Sample App manages to test this:

```
XCTAssertEqual(view.rightButton.enabled, data["buttonEnabled"] as? Bool ?? false)
```

The tests pass indicating that the button is correctly enabled/disabled.

What does your `viewForData` method look like?

**Comment by buppal** [comment]
That's interesting. I have attached my view and ViewTests. If you see in the code I am sending you, the info button should be visible half of the times, and not visible for the other half.

[LayoutTestCode.zip](https://github.com/linkedin/LayoutTest-iOS/files/452977/LayoutTestCode.zip)

**Comment by plivesey** [comment]
So to be clear, this line gets called:

`infoButton.hidden = !viewModel.shouldShowPriceBreakdown`

and `viewModel.shouldShowPriceBreakdown` is sometimes `true` and sometimes `false`.

But, when you inspect the value of hidden, it's always false?

**Comment by buppal** [comment]
Yes. To put it in a more clear way, viewModel.shouldShowPriceBreakdown is sometimes `true` and sometimes `false`. But in the index.html, the view always shows. It should show/not show according to this bool, and that does not seem to work.

**Comment by plivesey** [comment]
so, the index.html only shows views which have errors. Perhaps you are only failing the test when this view is being shown? For instance, if a view is overlapping this view, it will only fail when this view is not hidden.

**Comment by buppal** [comment]
Oh no. I purposely put an XCTAssert to assert and see the views.

**Comment by plivesey** [comment]
To debug this, you could try putting `XCTFail()` in the block for your test. This will cause every view to fail and you'll see all views in the `index.html`.

**Comment by plivesey** [comment]
Ah, yeah...looks like you did this. When you query the view for `infoButton.hidden` it gives you the right answer correct?

**Comment by buppal** [comment]
yes.

**Comment by plivesey** [comment]
So, the bug here is that the screenshot logic seems to not be working. Let me see if I can repro.

**Comment by buppal** [comment]
Yes right. May be it is hardcoded to true somewhere. That's what I can guess, but not sure.

**Comment by plivesey** [comment]
Meh...no dice again.

Changed the sample app to be:

```
    func setup(json: [NSObject: AnyObject]) {
        label.text = json["text"] as? String
        button.setTitle(json["buttonText"] as? String, forState: .Normal)
        label.hidden = true
    }
```
So the label is always hidden. When I run tests, I see all the views printed out (I added an `XCTFail()`) but the view is hidden.

**Comment by plivesey** [comment]
Could you try in your tests something like adding the current view to the window and see how it renders?

**Comment by buppal** [comment]
Ah that's interesting. I think may be we are calling the action `infoButtonTapped()`. This function in turn toggles the visibility of the info button. May be this is kind of dynamic and is not taken into account while rendering them in the html? Thoughts?

```
    static func viewForData(data: [NSObject: AnyObject], reuseView: UIView?,
                            size: LYTViewSize?, context: AutoreleasingUnsafeMutablePointer<AnyObject?>) -> UIView {
        let view = BundleSavingsAndTotalView(viewModel: FakeBundleSavingsAndTotalViewModel(data: data))
        let shouldShowPriceBreakdown = data["shouldShowPriceBreakdown"] as! Bool
        if shouldShowPriceBreakdown {
            view.infoButtonTapped()
        }
        return view
    }
}

    private func updatePriceBreakdownView(isVisible isVisible: Bool, animated: Bool) {
        if animated {
            UIView.animateWithDuration(animationDuration) {
                self.bundlePriceBreakdownView.hidden = !isVisible
            }
        } else {
            bundlePriceBreakdownView.hidden = !isVisible
        }
        infoButton.hidden = isVisible
    }

```

**Comment by plivesey** [comment]
Well, when you call `animateWithDuration`, it actually changes the `.hidden` value immediately. Only the layer value will change.

Currently, layout tests aren't setup up to do interactions well because they run synchronously. You could do this with waits, but probably not a great solution because of how slow they will run.

**Comment by buppal** [comment]
Oh ok, so you mean the data layer property will change, but the LayoutTest library wont take that into account? 

Probably I will write a UIViewController test for interactions and test only layout with UILayoutTests.

**Comment by buppal** [comment]
Closing this issue, got why that was happening, probably expected behavior. Thanks for the help!
