### ISSUE TITLE
Missing SWIFT_VERSION in project file

### ISSUE THREAD

**Issue by brennantaylor** [linkedin/LayoutTest-iOS#25]
It appears that the project does not have the `SWIFT_VERSION` build setting set. When building with Xcode 8 I get:

```
Use Legacy Swift Language Version (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

**Comment by plivesey** [comment]
Yeah, haven't migrated to new versions of swift yet. Currently going through all of our open source libs and fixing them up.

I can work on this next though if it'd help. Are you moving to Swift 3?

**Comment by brennantaylor** [comment]
No just 2.3.

It would be nice if there was a 2.3 release regardless so anyone looking to migrate slowly has the option. Most other open source libraries are doing this as well.

**Comment by plivesey** [comment]
#26

**Comment by plivesey** [comment]
Are you using Carthage? This shouldn't affect cocoapods afaik.

**Comment by plivesey** [comment]
Done, but struggling to get travis working...

**Comment by brennantaylor** [comment]
Yeah Carthage. Cocoapods is affected, you are able to write a little snippet of code to inject the SWIFT_VERSION into the project files.

**Comment by plivesey** [comment]
Yep. Will release since I get travis going. Maybe will be tomorrow morning at this rate.
Travis was down for a while this afternoon.

**Comment by plivesey** [comment]
https://travis-ci.org/linkedin/LayoutTest-iOS/builds/161701390

**Comment by brennantaylor** [comment]
I can checkout and test with the commit in your PR.

**Comment by plivesey** [comment]
Released version 1.4.0.

Feel free to reopen if it doesn't work.

**Comment by brennantaylor** [comment]
Thanks. Testing now.

**Comment by brennantaylor** [comment]
Looks like it built fine. Testing my main project next.

**Comment by brennantaylor** [comment]
All good 👍
