### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by ashfurrow** [linkedin/LayoutTest-iOS#3]
Hey there! Really interesting project! I'm a bit confused about the motivation of the tool; like, what problem does this solve, and how is it better than other solutions? I'd love to see an explanation in the readme, maybe like a before-and-after using this library. 

Thanks again! Really cool!

**Comment by plivesey** [comment]
Thanks for the feedback. I think there is a decent overview in the docs (http://linkedin.github.io/LayoutTest-iOS/pages/010_overview.html) but I'm assuming your suggestion here is that you don't want to click through to the docs to get to this information.

To answer your question:
Motivation is mostly that view layout code tends to include a lot of logic and most of this logic tends to go untested. The closest we get is running some UI automation tests which at least load some data into the view but rarely make assertions about the business logic we've written (e.g. if liked==true then the button should be selected).
This library provides an easy way to define data specs which generate many different combinations of data. You can then inflate your views using this data and write assertions on your view.
The library also runs a bunch of automatic tests which catch common problems such as missing accessibility, autolayout errors and overlapping views.

I'll work on adding more stuff to the README to give a better overview.

**Comment by plivesey** [comment]
Updated the README with a motivation section. Let me know what you think...and also if you know how to center the image in a README...

Going to close this ticket.

**Comment by ashfurrow** [comment]
Cool! Looks better :+1: It's not that _I_ didn't want to click through, but I think the project would benefit from having that info in the readme, since I think other people might not :wink: In any case, looks great!

**Comment by orta** [comment]
Big improvements, great job!
