### ISSUE TITLE
carthage update LayoutTest-iOS at "3.0.0" latest version builds LayoutTestCase.swift incorrectly

### ISSUE THREAD

**Issue by rodriguv** [linkedin/LayoutTest-iOS#39]
When it kept failing during the build scheme phase, i decided to compare in Kaleidoscope the  LayoutTestCase.swift it built vs the one in the visible repo here. I attached the snapshots of the failure that pointed to that file and of the kaleidoscope comparison. Any reasons as to why this happens?

<img width="1189" alt="diff" src="https://user-images.githubusercontent.com/16788537/28348891-9a48f40c-6c0d-11e7-8d57-1e4646d5be5c.png">
<img width="1435" alt="terminal_error" src="https://user-images.githubusercontent.com/16788537/28348892-9a490a82-6c0d-11e7-97fe-e47e95087ca0.png">

**Comment by mpdifran** [comment]
The released version of LayoutTest does not have this bug fix. You'll have to wait until the next version is released, or point Carthage directly to master.

**Comment by drumnkyle** [comment]
Released version was updated. Please reopen if this is still an issue.
