### ISSUE TITLE
Layout is not updated with new input data

### ISSUE THREAD

**Issue by KotiJocki** [linkedin/LayoutTest-iOS#4]
- Construct a view with two labels where one label will overlap another when a long string is used. 
- Run a test case that provides a very long string as the only input for one of the labels and observe this test failing as expected.
- Run another test case that provides LYTStringValues() and observe that the expected failing test passes.

**Comment by KotiJocki** [comment]
Working on a fix involving setNeedsLayout and layoutIfNeeded

**Comment by plivesey** [comment]
Copied from commenting on the last commit:

A couple of questions:
1) I definitely think this is necessary (clearly shown by your unit test), but do you know why this is necessary? As in, what does setNeedsLayout do that layoutIfNeeded doesn't do?
2) This will cause some tests which currently pass to fail, right? Given this, would you consider this a backwards incompatible change? It's not compile breaking, but it is project breaking. If we consider this backwards incompatible, then we'll have a lot of major version bumps in this library (but that's not a bad thing).

Thanks for fixing this btw.

**Comment by plivesey** [comment]
Btw, I ran this on our app at LinkedIn and we have 7 failures (2 tests failing) in ~100 total tests. So leaning towards categorizing this as backwards incompatible.

**Comment by plivesey** [comment]
Merged the pull request.

**Comment by plivesey** [comment]
I've released a new version 1.1.1 with these changes.
