### ISSUE TITLE
How to use it with UIViewController?

### ISSUE THREAD

**Issue by anirudhamahale** [linkedin/LayoutTest-iOS#41]
`(UIView *)viewForData:(NSDictionary *)data reuseView:(nullable UIView *)reuseView size:(nullable LYTViewSize *)size context:(id _Nullable * _Nullable)context;` this function takes an object of UIView so how to use object of UIViewController? as I have all my IBOutlets connnected to UIViewController.

**Comment by anirudhamahale** [comment]
Here are the steps which I followed:- 
1. Get the ViewController by instantiating it.
2. Assign the ViewController to the context.

**Comment by drumnkyle** [comment]
Yep. You are correct. Thank you for answering your question. Sorry I didn’t get to it sooner. This is covered in my [LinkedIn Learning](Check this out on LinkedIn Learning: https://www.linkedin.com/learning/learning-layouttest-for-ios-development?trk=share_ios_course_learning).
